HairSalon/Models/Client.cs
using System.Collections.Generic;
using MySqlConnector;

namespace HairSalon.Models
{
  public class Client
  {
    public int ClientId { get; set; }

    public string Name { get; set; }
    public int StylistId { get; set; }
    public Stylist Stylist { get; set; }
  }
}

HairSalon/Models/HairSalonContext.cs
using Microsoft.EntityFrameworkCore;

namespace HairSalon.Models
{
  public class HairSalonContext : DbContext
  {
    public DbSet<Stylist> Stylists { get; set; }
    public DbSet<Client> Clients { get; set; }

    public HairSalonContext(DbContextOptions options) : base(options) { }
  }
}

HairSalon/Models/Stylist.cs
using System.Collections.Generic;

namespace HairSalon.Models
{
  public class Stylist
  {
      public int StylistId { get; set; }
      public string Name { get; set; }
      public List<Client> Clients { get; set; }
  }
}

HairSalon/Controllers/ClientsController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HairSalon.Controllers
{
  public class ClientsController : Controller
  {
    private readonly HairSalonContext _db;

    public ClientsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
        List<Client> model = _db.Clients
                              .Include(client => client.Stylist)
                              .ToList();
        return View(model);
    }

    public ActionResult Create()
    {
      ViewBag.StylistId = new SelectList(_db.Stylists, "StylistId", "Name");
      return View();
    }

    [HttpPost]
    public ActionResult Create(Client client)
    {
        _db.Clients.Add(client);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      Client thisClient = _db.Clients
                          .Include(client => client.Stylist)
                          .FirstOrDefault(client => client.ClientId == id);
      return View(thisClient);
    }

    public ActionResult Edit(int id)
    {
        Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
        ViewBag.SylistId = new SelectList(_db.Stylists, "SylistId", "Name");
        return View(thisClient);
    }

    [HttpPost]
    public ActionResult Edit(Client client)
    {
        _db.Clients.Update(client);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
        Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
        return View(thisClient);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
        Client thisClient = _db.Clients.FirstOrDefault(client => client.ClientId == id);
        _db.Clients.Remove(thisClient);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
  }
}

HairSalon/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace HairSalon.Controllers
{
    public class HomeController : Controller
    {

      [HttpGet("/")]
      public ActionResult Index()
      {
        return View();
      }

    }
}

HairSalon/Controllers/StylistsController.cs
using Microsoft.AspNetCore.Mvc;
using HairSalon.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;


namespace HairSalon.Controllers
{
  public class StylistsController : Controller
  {
    private readonly HairSalonContext _db;

    public StylistsController(HairSalonContext db)
    {
      _db = db;
    }

    public ActionResult Index()
    {
      List<Stylist> model = _db.Stylists.ToList();
      return View(model);
    }

    public ActionResult Create()
    {
        return View();
    }

    [HttpPost]
    public ActionResult Create(Stylist stylist)
    {
        _db.Stylists.Add(stylist);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult Edit(int id)
    {
        Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
        return View(thisStylist);
    }

    [HttpPost]
    public ActionResult Edit(Stylist Stylist)
    {
        _db.Stylists.Update(Stylist);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
        Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
        return View(thisStylist);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
        Stylist thisStylist = _db.Stylists.FirstOrDefault(stylist => stylist.StylistId == id);
        _db.Stylists.Remove(thisStylist);
        _db.SaveChanges();
        return RedirectToAction("Index");
    }
    public ActionResult Details(int id)
    {
      Stylist thisStylist = _db.Stylists
                                  .Include(stylist => stylist.Clients)
                                  .FirstOrDefault(stylist => stylist.StylistId == id);
      return View(thisStylist);
    }
  }
}

HairSalon/Views/Clients/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<p><strong>NOTE:</strong> You need to have at least one stylist before you can add a client!</p>
<p>Go to @Html.ActionLink("this page", "Create", "Stylists") to create a stylist.</p>
<h4>Add a new client</h4>
@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name)

    @Html.LabelFor(model => model.Stylist)
    @Html.DropDownList("StylistId")
    <input type="submit" value="Add new client" class="btn btn-primary" />
}
<p>@Html.ActionLink("Show all clients", "Index")</p>

HairSalon/Views/Clients/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Are you sure you want to delete this client?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
    <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

HairSalon/Views/Clients/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Client Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>
<h3>@Html.DisplayNameFor(model => model.Stylist): @Html.DisplayFor(model => model.Stylist.Name)<h3>
<p>@Html.ActionLink("Edit Client", "Edit", new { id = Model.ClientId })</p>
<p>@Html.ActionLink("Delete Client", "Delete", new { id = Model.ClientId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

HairSalon/Views/Clients/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Client

<h2>Edit</h2>

<h4>Edit this client: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.ClientId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name)

    @Html.LabelFor(model => model.Stylist)
    @Html.DropDownList("StylistId")

    <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

HairSalon/Views/Clients/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;
@model List<HairSalon.Models.Client>;

<h1>Clients</h1>

@if (@Model.Count == 0)
{
  <h3>No clients have been added yet!</h3>
} 
else
{
  <ul>
    @foreach (Client client in Model)
    {
      <li>@Html.ActionLink($"{client.Name}", "Details", new { id = client.ClientId }) | @client.Stylist.Name</li>
    }
  </ul>
}

<p>@Html.ActionLink("Add new client", "Create")</p>

HairSalon/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Welcome to Claire's Client Tracker!</h1>
<p>@Html.ActionLink("See all clients", "Index", "Clients")</p> 
<p>@Html.ActionLink("See all stylists", "Index", "Stylists")</p>

HairSalon/Views/Shared/Footer.cshtml
<div id="footer"></div>

HairSalon/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Clair's Hair Salon</title>
    <link 
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" 
      rel="stylesheet" 
      integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" 
      crossorigin="anonymous"> 
    <link rel="stylesheet" href="~/css/styles.css">
  </head>
  <body>
    @RenderBody()
    @await Html.PartialAsync("Footer")
  </body>
</html>

HairSalon/Views/Stylists/Create.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h4>Add a new stylist</h4>
@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)
  <input type="submit" value="Add new stylist" />
}
<p>@Html.ActionLink("Show all stylists", "Index")</p>

HairSalon/Views/Stylists/Delete.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}
@Html.ActionLink("Back to List", "Index")

HairSalon/Views/Stylists/Details.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist
@using HairSalon.Models

<h2>Stylist Details</h2>
<hr />
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)<h3>

@if (@Model.Clients.Count == 0)
{
  <h3>No clients have been added to this stylist yet!</h3>
} 
else
{
  <h3>Clients:</h3>
  <ul>
    @foreach (Client client in Model.Clients)
    {
      <li>@Html.ActionLink($"{client.Name}", "Details", "Clients", new { id = client.ClientId })</li>
    }
  </ul>
}

<p>@Html.ActionLink("Edit Stylist", "Edit", new { id = Model.StylistId })</p>
<p>@Html.ActionLink("Delete Stylist", "Delete", new { id = Model.StylistId })</p>
<p>@Html.ActionLink("Back to list", "Index")</p>

HairSalon/Views/Stylists/Edit.cshtml
@{
  Layout = "_Layout";
}

@model HairSalon.Models.Stylist

<h2>Edit</h2>

<h4>Edit this stylist: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.StylistId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)

  <input type="submit" value="Save" />
}
<p>@Html.ActionLink("Back to list", "Index")</p>

HairSalon/Views/Stylists/Index.cshtml
@{
  Layout = "_Layout";
}

@using HairSalon.Models;

<h1>Stylists</h1>

@if (@Model.Count == 0)
{
  <h3>No stylists have been added yet!</h3>
} 

<ul>
  @foreach(Stylist stylist in Model)
  {
    <li>@Html.ActionLink($"{stylist.Name}", "Details", new { id = stylist.StylistId })</li>
  }
</ul>

<p>@Html.ActionLink("Add new stylist", "Create")</p>
<p>@Html.ActionLink("Add new Client", "Create", "Clients")</p>
<p>@Html.ActionLink("Home", "Index", "Home")</p>